export const actionTypes = Object.freeze({
  ORDERS_START_FETCHING: 'ORDERS_START_FETCHING',
  ORDERS_STOP_FETCHING: 'ORDERS_STOP_FETCHING',
  ORDERS_SET_FETCHING_ERROR: 'ORDERS_SET_FETCHING_ERROR',

  ORDERS_FILL: 'ORDERS_FILL',

  ORDERS_FETCH_ASYNC: 'ORDERS_FETCH_ASYNC',
});
