export const actionTypes = Object.freeze({
  LOGIN_START_FETCHING: 'LOGIN_START_FETCHING',
  LOGIN_STOP_FETCHING: 'LOGIN_STOP_FETCHING',
  LOGIN_SET_FETCHING_ERROR: 'LOGIN_SET_FETCHING_ERROR',

  LOGIN_SET_STATUS: 'LOGIN_SET_STATUS',
  LOGIN_FILL: 'LOGIN_FILL',

  LOGIN_FETCH_ASYNC: 'LOGIN_FETCH_ASYNC',
});
