export const actionTypes = Object.freeze({
  SIGNUP_START_FETCHING: 'SIGNUP_START_FETCHING',
  SIGNUP_STOP_FETCHING: 'SIGNUP_STOP_FETCHING',
  SIGNUP_SET_FETCHING_ERROR: 'SIGNUP_SET_FETCHING_ERROR',

  SIGNUP_SET_STATUS: 'SIGNUP_SET_STATUS',
  SIGNUP_FILL: 'SIGNUP_FILL',

  SIGNUP_FETCH_ASYNC: 'SIGNUP_FETCH_ASYNC',
});
