export const actionTypes = Object.freeze({
  INGREDIENTS_START_FETCHING: 'INGREDIENTS_START_FETCHING',
  INGREDIENTS_STOP_FETCHING: 'INGREDIENTS_STOP_FETCHING',
  INGREDIENTS_SET_FETCHING_ERROR: 'INGREDIENTS_SET_FETCHING_ERROR',

  INGREDIENTS_FILL: 'INGREDIENTS_FILL',

  INGREDIENTS_FETCH_ASYNC: 'INGREDIENTS_FETCH_ASYNC',
});
