export const checkoutActionTypes = Object.freeze({
  CHECKOUT_START_FETCHING: 'CHECKOUT_START_FETCHING',
  CHECKOUT_STOP_FETCHING: 'CHECKOUT_STOP_FETCHING',
  CHECKOUT_SET_FETCHING_ERROR: 'CHECKOUT_SET_FETCHING_ERROR',

  CHECKOUT_FILL: 'CHECKOUT_FILL',
  CHECKOUT_SET_ACCEPT: 'CHECKOUT_SET_ACCEPT',

  CHECKOUT_SEND_DATA_ASYNC: 'CHECKOUT_SEND_DATA_ASYNC',
});